In [1]:
import pandas as pd
df = pd.read_csv("iris.csv")
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [2]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df["Species"] = le.fit_transform(df["Species"])

In [3]:
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0   1            5.1           3.5            1.4           0.2        0
1   2            4.9           3.0            1.4           0.2        0
2   3            4.7           3.2            1.3           0.2        0
3   4            4.6           3.1            1.5           0.2        0
4   5            5.0           3.6            1.4           0.2        0

In [4]:
X = df.drop(["Species"],axis=1)
y = df["Species"]
from sklearn.model_selection import train_test_split
X_train , X_test , y_train, y_test = train_test_split(X ,y , test_size=0.3)

In [7]:
from sklearn.pipeline import Pipeline
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB

# Dictionary of models
models = {
    'knn': KNeighborsClassifier(),
    'lr': LogisticRegression(),
    'nv': GaussianNB()
}

# Loop through models
for name, model in models.items():

    pipeline = Pipeline([
        ('scale', StandardScaler()),
        ('model', model)
    ])

    # Different parameter grids
    if name == 'knn':

        param_grid = {
            "model__n_neighbors": [3,5,7,9,11,13,15,17]
        }

    elif name == 'lr':

        param_grid = {
            "model__C": [0.01, 0.1, 1, 10]
        }

    else:
        param_grid = {}

    # GridSearchCV
    classifierCV = GridSearchCV(
        pipeline,
        param_grid,
        cv=5
    )

    classifierCV.fit(X_train, y_train)

    print(f"{name} best params:", classifierCV.best_params_)
    print(f"{name} best score :", classifierCV.best_score_)
    print()

knn best params: {'model__n_neighbors': 3}
knn best score : 1.0

lr best params: {'model__C': 10}
lr best score : 1.0

nv best params: {}
nv best score : 0.9904761904761905